[package]
name = "zome_tagging_integrity"
version.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies]
serde.workspace = true
hdi.workspace = true
zome_utils.workspace = true
